[module/tray]
type = internal/tray
inherit = base/module-left
; The action format code is to send a signal to the toggling script
format = <tray>
hidden = false
tray-size = 32
tray-maxsize = 32
tray-spacing = 3
tray-background = ${colors.bg-left}
