font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11

background_opacity 0.9
background_blur 5
dynamic_background_opacity yes

linux_display_server wayland
wayland_enable_ime no
sync_to_monitor no
confirm_os_window_close 0
shell_integration enabled
startup_session default.kitty-session
scrollbar always
mouse_hide_wait 1
visual_bell_duration 0
visual_bell_color none
window_alert_on_bell yes
bell_on_tab "🔔 "

map ctrl+shift+f launch --type=window --stdin-source=@screen_scrollback fzf --no-sort --no-mouse --exact -i
enabled_layouts splits,tall,fat,stack,grid
map ctrl+shift+backslash launch --location=vsplit
